# --- copy this file to /etc/apache2/proxy-configs

# Proxy settings for /example_provider

# Enable mod_rewrite
RewriteEngine On

# Capture the original request URI and store it in an environment variable
RewriteCond %{REQUEST_URI} (.*)
RewriteRule .* - [E=ORIGINAL_URI:%{REQUEST_URI}]

# Ensure that mod_headers uses the environment variable correctly
Header set X-Original-URI "%{ORIGINAL_URI}e"

ProxyPreserveHost On
ProxyPass /example_provider http://localhost:8000/
ProxyPassReverse /example_provider http://localhost:8000/
ProxyAddHeaders On
