# --- copy this file to /etc/apache2/proxy-configs

# Proxy settings for /servicenow
ProxyPreserveHost On
ProxyPass /servicenow http://localhost:8000/
ProxyPassReverse /servicenow http://localhost:8000/
