# --- copy this file to /etc/supervisor/conf.d

[program:example_provider]
priority=10
stopasgroup=true
command=datahub_server --module_path /srv/example_provider/src --port 8000 --host 127.0.0.1
autostart=true
autorestart=true
stdout_logfile=/var/log/example_provider/example_provider.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
redirect_stderr=true
