# --- copy this file to /etc/supervisor/conf.d

# modify provider name as needed
[program:example_provider]

# change root to a service user for security reasons
user=root

# modify provider name and port as needed
command=bash -c "source /srv/example_provider/venv/bin/activate && datahub_server --module_path /srv/example_provider/src --port 8000 --host 127.0.0.1"
stdout_logfile=/var/log/example_provider/example_provider.log

priority=10
stopasgroup=true
autostart=true
autorestart=true
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
redirect_stderr=true
