# --- copy this file to /etc/supervisor/conf.d

[program:example_provider]

environment=PROVIDER_NAME='example_provider',PORT='8000',USER='root'

priority=10
stopasgroup=true
command=/srv/%(ENV_PROVIDER_NAME)/venv/bin/python datahub_server --module_path /srv/%(ENV_PROVIDER_NAME)/src --port %(ENV_PORT) --host 127.0.0.1
user=%(ENV_USER)
autostart=true
autorestart=true
stdout_logfile=/var/log/%(ENV_PROVIDER_NAME)/%(ENV_PROVIDER_NAME).log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
redirect_stderr=true
